### ISSUE TITLE
proc-sys-fs-binfmt_misc.automount: Failed to initialize automounter: Operation not permitted

### ISSUE THREAD

**Issue by sanzenwin** [nestybox/sysbox-ee#49]
`docker run  -it --runtime=sysbox-runc --privileged  --restart=always  -p 9200:9000  nestybox/ubuntu-bionic-systemd-docker:latest`

1. running log:
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Reached target Remote File Systems.
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Created slice User and Session Slice.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Swap.
[  OK  ] Created slice System Slice.
[  OK  ] Listening on udev Kernel Socket.
[  OK  ] Listening on udev Control Socket.
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe.
proc-sys-fs-binfmt_misc.automount: Failed to initialize automounter: Operation not permitted
[FAILED] Failed to set up automount Arbitrary Executable File Formats File System Automount Point.
See 'systemctl status proc-sys-fs-binfmt_misc.automount' for details.

2. run `systemctl status proc-sys-fs-binfmt_misc.automount`  on the container:
● proc-sys-fs-binfmt_misc.automount - Arbitrary Executable File Formats File System Automount Point
   Loaded: loaded (/lib/systemd/system/proc-sys-fs-binfmt_misc.automount; static; vendor preset: enabled)
   Active: failed (Result: resources)
    Where: /proc/sys/fs/binfmt_misc
     Docs: https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html
           https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems

3. run `docker info`  on host machine :
Client:
 Debug Mode: false
Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 57
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc sysbox-runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-72-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.645GiB
 Name: sanzenwin
 ID: 2YUT:QA42:UWRF:X2M7:LTJY:TJN7:SCND:BY24:QRJZ:VJ5X:R4PC:Z5YY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://ustc-edu-cn.mirror.aliyuncs.com/
 Live Restore Enabled: false
WARNING: No swap limit support

4. run `uname -a` on host machine:
Linux ***** 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rodnymolina** [comment]
Hi @sanzenwin, thanks for reporting this issue.

Please be aware that Sysbox doesn't support the "--privileged" flag as documented [here](https://github.com/nestybox/sysbox/blob/1f12f717ca8c892054114628d978b8c19c44dbab/docs/user-guide/limitations.md#support-for-dockers---privileged-option).

Please try again without this flag and let us know if you see any issue.

**Comment by rodnymolina** [comment]
There's some room for improvement from our side though as we should proactively log a warning message to alert the user of the lack of support for this flag.

**Comment by sanzenwin** [comment]
> Hi @sanzenwin, thanks for reporting this issue.
> 
> Please be aware that Sysbox doesn't support the "--privileged" flag as documented [here](https://github.com/nestybox/sysbox/blob/1f12f717ca8c892054114628d978b8c19c44dbab/docs/user-guide/limitations.md#support-for-dockers---privileged-option).
> 
> Please try again without this flag and let us know if you see any issue.

It works, Thanks.

**Comment by rodnymolina** [comment]
Closing issue now.
